#!/usr/bin/bash
this_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
sudo pacman -Syyu
sudo pacman -Sy --needed curl wget rsync zstd htop git zoxide bat fzf ncdu micro lf mcfly terminus-font net-tools dog shellcheck fastetch arp-scan nmap


printf '%s\n' "EDITOR=micro\nVISUAL=micro" | sudo tee -a /etc/enviroment
printf '%s\n' "MANPAGER=\"sh -c 'col -bx | bat -l man -p'\"" | sudo tee -a /etc/environment
printf '%s\n' "${USER} ALL=(ALL:ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers.d/${USER}

cp -rbv $this_dir/src/user/. $HOME/

tee -a $HOME/.bashrc <<_END_
# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "\$rc" ]; then
			. "\$rc"
		fi
	done
fi
unset rc
_END_
setfont ter-124b
